spring:
  application:
    name: springboot.eureka

server:
  port: 8761

eureka:
  instance:
    hostman: eureka.server1
  client:
    serviceUrl:
      defaultZone: "http://localhost:8762/eureka/"
    register-with-eureka: true
    fetch-registry: true
